import 'reflect-metadata';

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from '@/shared/components/Sidebar/Sidebar';
// import Sidebar from "../components/main/Sidebar";

// Styles
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} bg-system-primary-background text-black  w-screen h-screen flex flex-row`}>
        <ToastContainer />
        <div className="w-2/12 h-full p-5">
          <div className='w-full h-full rounded-lg bg-system-secondary-background'>
            <Sidebar />
          </div>
        </div>
        <div className="w-10/12 h-full p-5 flex">
          <div className="w-full h-full rounded-lg flex items-center justify-center bg-system-secondary-background">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
