"use client"
// import 'reflect-metadata';

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from '@/shared/components/Sidebar/Sidebar';
// import Sidebar from "../components/main/Sidebar";

// Styles
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import ShowHideIconButton from '@/shared/components/ShowHideIconButton/ShowHideIconButton';
import { useState } from 'react';
import { Collapse } from '@mui/material';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [sidebarOpen, setSidebarOpen] = useState<boolean>(true);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} bg-system-primary-background text-black w-screen h-screen overflow-hidden flex flex-row`}>
        <ToastContainer />
        <div className="relative flex max-w-[600px]">
          <Collapse in={sidebarOpen} orientation="horizontal">
            <div className="h-full p-5 shrink-0 relative z-20">
              <div className='w-full h-full rounded-lg bg-system-secondary-background'>
                <Sidebar />
              </div>
            </div>
          </Collapse>
          {/* Toggle button - stays at right edge of sidebar area */}
          <div className="absolute -right-5 top-1/2 -translate-y-1/2 z-20 bg-white rounded-full">
            <ShowHideIconButton 
              horizontalHidding={true}
              tooltipTitle={"Menu principal"}
              onChangeButtonState={setSidebarOpen}
              leftDownInitialState={true}
              placement = "right" />
          </div>
        </div>
        <div className="w-full h-full p-5 flex min-w-0 relative z-10">
          <div className="w-full h-full rounded-lg flex items-center justify-center bg-system-secondary-background">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
